language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - .manage.py migrate
  - coverage run --source=. manage.py test
  - coverage report

after_success:
  - "coveralls"
  - "codeclimate-test-reporter"